name: Django CI
on:
  [push, pull_request]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd MySite
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

      - name: Run flake8
        run: |
          flake8
